version: '3.9'

services:
  chat-service:
    build:
      context: ./chat-service
    ports:
      - "8080:8080"
    restart: unless-stopped

  chat-gateway:
    build:
      context: ./chat-gateway
    ports:
      - "8081:8081"
    depends_on:
      - chat-service
    restart: unless-stopped

  chat-ai:
    build:
      context: ./chat-ai
    depends_on:
      - chat-service
    restart: unless-stopped

  #chat-client:
  #  build:
  #    context: ./chat-client
  #  ports:
  #    - "3000:3000"
  #  restart: unless-stopped