# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"V\n\x0b\x43hatMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0c\n\x04room\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"%\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1d\n\rStreamRequest\x12\x0c\n\x04room\x18\x01 \x01(\t\"1\n\x0bSendRequest\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.chat.ChatMessage2v\n\x0b\x43hatService\x12+\n\x0bSendMessage\x12\x11.chat.SendRequest\x1a\t.chat.Ack\x12:\n\x0eStreamMessages\x12\x13.chat.StreamRequest\x1a\x11.chat.ChatMessage0\x01\x42.Z,github.com/yourusername/go-chat/proto;chatpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/yourusername/go-chat/proto;chatpb'
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=106
  _globals['_ACK']._serialized_start=108
  _globals['_ACK']._serialized_end=145
  _globals['_STREAMREQUEST']._serialized_start=147
  _globals['_STREAMREQUEST']._serialized_end=176
  _globals['_SENDREQUEST']._serialized_start=178
  _globals['_SENDREQUEST']._serialized_end=227
  _globals['_CHATSERVICE']._serialized_start=229
  _globals['_CHATSERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
