name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  chat-service:
    name: Chat Service Build/Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Makefile inside Dev Container
        uses: devcontainers/ci@v0.3
        with:
          subFolder: chat-service
          runCmd: |
            make proto
            make build
            make test
            make fmt

  chat-ai:
    name: Chat AI Build/Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Makefile inside Dev Container
        uses: devcontainers/ci@v0.3
        with:
          subFolder: chat-ai
          runCmd: |
            make install
            make lint
            make build
            make test
