name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test All Projects
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build root dev container and run multi-service tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cd chat-service
            make proto
            make build
            make test
            make fmt
            cd ../chat-ai
            make install
            make lint
            make build
            make test
